### ISSUE TITLE
Settings button missing

### ISSUE THREAD

**Issue by xRyul** [hydescarf/Obsidian-Theme-Mado-11#1]
Not sure design or a feature. But I couldn't find the Settings button, thus unable to go back to the default theme if needed. Please add a warning., on how to get to the settings button. Or how to revert back to the default theme.

**Comment by hydescarf** [comment]
Unfortunately, this is the default design as this theme aims for simplified (or minimal) feels. There's no other way to add a warning except from reading the guideline in the preview image of the theme before installation, and then proceed to install those buttons manually with the instruction on github. A faulty design to be honest.  
  
To open up the settings, you can call them out with either the following:  
- Use the shortcut (Ctrl + ,)
- Search for "settings" from the Command Palette (Ctrl + P) if it's previously enabled in the core setting.  
  
On a second thought, maybe I can try something with hovers on the settings ribbon, will test it out in a few hours.

**Comment by hydescarf** [comment]
Previously hidden buttons (including new file/folder/rearrange buttons) are now hover-to-show in the latest version. https://github.com/hydescarf/Obsidian-Theme-Mado-11/commit/a54334a0478318f745269ea8ccbd0780b633d969

Settings, etc. buttons are positioned at the bottom-left corner, while the new file etc. buttons are at the top-right corner of the left sidebar. To not disturb the main buttons, you have to hover around the edge to make them appear.

Let me know if these work for you.
![タイトルなし](https://user-images.githubusercontent.com/56707567/164868909-41a30f61-db65-4225-b5df-2c4bd1e7eafd.png)
