### ISSUE TITLE
Optimize horizontal line spacing

### ISSUE THREAD

**Issue by midnightmercenary** [hydescarf/Obsidian-Theme-Mado-11#10]
I love this theme. However, I feel the placement of horizontal lines could be improved somewhat. For example, they jump several lines below where they're placed in editor mode. It would be great if horizontal lines could be moved higher up in their default placement, I personally use horizontal lines beneath headings and this behavior messes up the look of my notes in my opinion.

![image](https://user-images.githubusercontent.com/56935282/182864472-71c8b8fa-8282-4c40-8d86-33eb6f48fa63.png)

![image](https://user-images.githubusercontent.com/56935282/182864920-98cb1ae3-966c-4ee0-80c2-5c90cd02ea52.png)

**Comment by hydescarf** [comment]
Yea, I shouldn't really style that. I'll take the whole margin off them this weekend.

**Comment by hydescarf** [comment]
Update is live now! They are now reverted to their original height.

**Comment by midnightmercenary** [comment]
Looks great! Thanks!
