### ISSUE TITLE
[Bug] Dotpoints In Transcluded Notes

### ISSUE THREAD

**Issue by 8veStory** [hydescarf/Obsidian-Theme-Mado-11#11]
Hello! I'm really loving the theme, it's so beautifully designed 🥺! However, I noticed that dotpoints in transcluded notes may be styled weirdly.

Here's what I mean:
![image](https://user-images.githubusercontent.com/29248979/184118443-084517d7-f53d-478a-98bc-3d10b5de78ae.png)
![image](https://user-images.githubusercontent.com/29248979/184118500-8292e0a8-0ddf-45b2-ae7a-7dab3b20d2c9.png)

**System Information**
- OS: Tested on Fedora 36 and Debian 11
- Obsidian Version: 0.15.9

**Comment by hydescarf** [comment]
I think I know which caused this, will look into it, thank you for the report!

**Comment by 8veStory** [comment]
oh sorry! I just realised that I was meant to post this on the miniflow. I've reposted this there: https://github.com/hydescarf/Obsidian-Theme-Mado-Miniflow/issues/7

**Comment by hydescarf** [comment]
Oh, no worries, since both of them share the same issue anyway, I will backport some fixes to this theme as well.

**Comment by hydescarf** [comment]
With the latest v1.0.0 redesign, I have dropped the styling of markers and instead use the default as it is. So, it shouldn't cause issue anymore in the future.
