### ISSUE TITLE
Adapt to Obsidian 1.0

### ISSUE THREAD

**Issue by ganeshannt** [hydescarf/Obsidian-Theme-Mado-11#12]
I have been using Mado-11 as the primary theme for its minimalism and UI appearance. Obsidian v1.0 has introduced a lot of features like tabs and etc. As of now unable to experience the latest feature of obsidian v1.0 with Mado-11. it would be great if we upgrade the Mado-11 theme to get the latest obsidian feature.

**Comment by hydescarf** [comment]
Thank you for the reminder!
I've planned to update the theme to support v1.0, so don't worry, though it'll take some time as I have to rewrite the whole thing now.

**Comment by hydescarf** [comment]
The latest update of the theme is now adapted to the new Obsidian v1.0 redesign! Thank you for your wait!
