### ISSUE TITLE
[Bug] The setting menu is translucent when translucent window is opening

### ISSUE THREAD

**Issue by Alex-coder251** [hydescarf/Obsidian-Theme-Mado-11#14]
![image](https://user-images.githubusercontent.com/58896036/199000092-6245b07c-ebb3-4ac6-9075-323e49a1206d.png)

**Comment by hydescarf** [comment]
Fixed in https://github.com/hydescarf/Obsidian-Theme-Mado-11/commit/9017036b559a00c387c160e6a8de874c7726d16b !
I've also adjusted the background colours for other transparent buttons as well.
