### ISSUE TITLE
the bar in the bottom（right corner）is not showed

### ISSUE THREAD

**Issue by bxz400** [hydescarf/Obsidian-Theme-Mado-11#17]
![image.png](https://pic7.58cdn.com.cn/nowater/webim/big/n_v2a20e319444dd41df8cdf320fdc7228e4.png)
I cannot see the same bar shows in the picture in your theme.Is it deliberately designed?
Without the bar，I cannot switch the workspace simply.I cannot see the words，which are inmortant.
Your theme is remarkable，but if it didin't include the bar，I had to stop😭

**Comment by hydescarf** [comment]
If you don't mind, you can try and install "Style Settings" plugin, it has an option to revert the hidden bar back!

**Comment by hydescarf** [comment]
Closing thread for inactivity! (Also, somewhat solved since it is available as an option. Let me know however, if the option isn't working)
