### ISSUE TITLE
line height, paragraph spacing, justify

### ISSUE THREAD

**Issue by TheCodeverse** [hydescarf/Obsidian-Theme-Mado-11#18]
Hello! I hope to adjust the line height and paragraph spacing of the note text, and set the text to be justified, and to hide the blank status bar at the bottom.

**Comment by hydescarf** [comment]
I think these are best be done in CSS Snippets. Line height and paragraph spacing are part of the theme so I won't be changing them here.

As for the status bar, are you facing an issue with it? It is set to be hidden by default, and can be toggled through Style Settings.
But I'm not sure what you mean by blank status bar, do you mind describing it?

**Comment by hydescarf** [comment]
Closing thread as there seems to be no issue for now!
