### ISSUE TITLE
[Request] to avoid/remove !important for page width setting

### ISSUE THREAD

**Issue by efemkay** [hydescarf/Obsidian-Theme-Mado-11#2]
your inclusion of `!important` to increase specificity is interfered with collection of snippets. hope you can consider not using `!important` for this. this is because, if i understand correctly, i can only override it by having an `!important` and then put more css classes. in this case, i have a snippet to control with of specific pages and if i use ur theme, the snippet can no longer work.

perhaps u use doubling of last class e.g. `.markdown-preview-view.is-readable-line-width .markdown-preview-sizer.markdown-preview-sizer` for you to override app's default css (in fact i believe, even with same specificity, snippets take priority).

thank you. btw i really love the clean look of your theme.

![image](https://user-images.githubusercontent.com/42369515/164950260-af978d63-718e-4664-b030-ef3864f67c24.png)

**Comment by hydescarf** [comment]
Thank you for the heads up!
Upon investigating, the `!important` was not important to the "preview" and multiple classes did the trick for "source".
I will also continue fixing the rest of the code that has `!important` in it in a few hours, though some of them have to use it to override inline class by Obsidian.

And thank you for the like ❤️

**Comment by hydescarf** [comment]
Most of the `!important` elements are now removed in the latest update: https://github.com/hydescarf/Obsidian-Theme-Mado-11/commit/c3cf44bacdb6ed7769d7adfedbdf212887d9d424
Some are kept as to override Obsidian inline-styling:
- markdown quote styling
- markdown hierarchy-list styling
- top-left back/forward button
- left-sidebar styling (which is crucial for this theme)
- right-sidebar styling (for docked notes, not too crucial, but for nicer visual)


I have also changed the part for the note padding (especially source-view)
```
.markdown-preview-view{
	padding-inline:63px;
}
.markdown-source-view .cm-content{
	padding-inline:13px;
}
```
It might affect your WIP snippets, so just a head up in case something changes on your side.

Let me know if these works well for you!

**Comment by efemkay** [comment]
Thanks! Sorry only managed to test it just now. Works fine with my snippet now (i don't have to change anything at all). Appreciate it!
