### ISSUE TITLE
Usage of css classes

### ISSUE THREAD

**Issue by DuraGit** [hydescarf/Obsidian-Theme-Mado-11#20]
@hydescarf 
For someone who does not know HTML and CSS could give an example on how to use the CSS classes, specifically the timelines and panels CSS classes ?

**Comment by hydescarf** [comment]
By Timelines & Panels, do you mean these elements? https://github.com/hydescarf/Obsidian-Theme-Mado-11/blob/main/img/mado-panel.png

It's a frontmatter/metadata thing, basically, **_on top of the note_** you want to apply the effects, insert the following:
```
---
cssclass: mado-panel
---
```

You can follow the guide page here for more information: https://help.obsidian.md/Editing+and+formatting/Metadata

---

As for the Mado Panel, there's also "callout" version of it where you can apply for certain individual without affecting the whole note, just like this:
```
> [!mado-panel]
> - This is a callout, now turned into listed panels
```
Which, you can also find more information about it here: https://help.obsidian.md/Editing+and+formatting/Callouts
If you are not sure, just let me know again!

**Comment by hydescarf** [comment]
Closing thread! Feel free to reopen it if you have any further questions about it!
