### ISSUE TITLE
Left sidebar is not working

### ISSUE THREAD

**Issue by jsmm** [hydescarf/Obsidian-Theme-Mado-11#3]
This is a very nice theme. Unfortunately, left sidebar is working for File Explorer, but not for Backlinks, Outgoing Links, Outline, Longform... If you need any further details, please let me know.

**Comment by hydescarf** [comment]
Thank you for trying out!
Technically, the left sidebar in this theme is only intended for file explorers and custom markdown for extra buttons below.
That being said, I did a simple fix to allow the other plugins to work.
```
.mod-left-split .workspace-tabs .view-content div{
	height:100%;
}
```
to
```
.mod-left-split .workspace-tabs .view-content .markdown-preview-view div{
	height:100%;
}
```

However, there won't be much custom styling for them (except a border to distinguish the tabs)
![タイトルなし](https://user-images.githubusercontent.com/56707567/165186319-405e9366-e8f7-473b-bf70-2d7f9175bdd2.png)

If that looks sufficient enough, then let me know and I'll push the update!
