### ISSUE TITLE
Incompatible with "Banners" plugin in Reader view

### ISSUE THREAD

**Issue by midnightmercenary** [hydescarf/Obsidian-Theme-Mado-11#5]
The Mado 11 theme and Banners plugin are incompatible with each other in Reader view. Maybe yaml frontend has something to do with it.
![image](https://user-images.githubusercontent.com/56935282/165307658-8be33aaa-3733-43e9-9f16-d4f21922096c.png)

**Comment by hydescarf** [comment]
Apparently, the animation was the culprit for it. Found a way to fix it but not sure why it happens 🤔 
Anyway, this will be updated along with the left-sidebar issue! Thank you for the report.
