### ISSUE TITLE
Top Left Window Buttons Overlap

### ISSUE THREAD

**Issue by whereiswhere** [hydescarf/Obsidian-Theme-Mado-11#6]
I tested it on Mac, if put mouse on the top left window, the buttons will overlap with the Obsidian's Go back and Go Forward buttons:

<img width="155" alt="Screen Shot 2022-05-20 at 5 44 27 PM" src="https://user-images.githubusercontent.com/27719991/169502077-c319a9cd-be3a-4310-a0af-c90275208ef9.png">

**Comment by hydescarf** [comment]
Unfortunately, I do not have a Mac to test this out.

If you don't mind helping out, can you try to use the "default theme", then open up the developer tools through `Cmd + Shift + I`.
Then click on the far-left icon with an arrow inside it.
![image](https://user-images.githubusercontent.com/56707567/169504178-05570759-55ae-4791-91db-2df0aab358dd.png)
Next, click on the close button, and take a screenshot of the whole developer tools like below
![image](https://user-images.githubusercontent.com/56707567/169505475-cf9f6f91-0ad8-46d6-b666-13c1c50095e2.png)

Specifically, I'd like to see the contents of `<div class="titlebar-inner">` to look for Mac-specific CSS class.

**Comment by whereiswhere** [comment]
Ok, like this? 

<img width="881" alt="Screen Shot 2022-05-21 at 1 26 17 AM" src="https://user-images.githubusercontent.com/27719991/169581196-760a1ef1-bc75-4c6d-be5c-1defbf357aa0.png">

**Comment by hydescarf** [comment]
Ah yes, thank you!
I see how I can fix this now, just have to apply a new CSS for `mod-macos` for the buttons.
And I see the right-side buttons for close/etc. are removed as well in this mode.

The new update is now live! https://github.com/hydescarf/Obsidian-Theme-Mado-11/commit/fc448530c0a8ba147716eb3df0f443a7e0945b35
Closing thread now but let me know if the problem persists.
